trainer:
  max_steps: 300000          # adjust to dataset size
  precision: 16-mixed
  log_every_n_steps: 50
  val_check_interval: 2000   # validate every N steps
  accelerator: auto
  devices: auto
  deterministic: false

logging:
  wandb:
    project: spatio-temporal-diffusion
    entity: glennwithtwons      # change if needed
    run_name: ddpm_baseline_30y
    mode: online                # {online|offline|disabled}
    save_code: true

checkpoints:
  dirpath: models/checkpoints
  monitor: val/mae_recon        # recon MAE on Î”+HFI_t
  mode: min
  save_top_k: 3
  every_n_train_steps: 2000

evaluation:
  # small-K sampling during val to ensure the ensemble path works
  ensemble_K_val: 4
  sampler:
    method: ddpm                # {ddpm|dpmpp}
    steps: 30
    tau: 1.0
    cfg_scale: 0.0              # off for baseline

repro:
  seed: 1337
